### PR TITLE
More wording edits

### PR DESCRIPTION
**Pull request by jni**

### CODE REVIEW

**Comment by jni** [comment]
Grrrr. Ok I'll rebase. =P

**Comment by emmanuelle** [comment]
No please don't I'm merging manually !

**Comment by emmanuelle** [comment]
It's a good way for me to compare your changes so I prefer to do it the manual way.

**Comment by emmanuelle** [comment]
I should be done in a few minutes!

**Comment by emmanuelle** [comment]
OK I merged!

**Comment by jni** [comment]
Oh LOL, cool thanks!!! =)

**Pull request merged**
